```{r}

load("All_list_for_prod.Rda")

library(colorspace)
library(dplyr)

colores_10 <- rainbow_hcl(10, end=300)
year_names <- c(2006:2015)

```

```{r}
names(All_list_for_prod[[1]])


Productivity_list_mean <- list()
for(k in 1:length(All_list_for_prod)){
    print(k)
  
All_list_for_prod[[k]] <- na.omit(All_list_for_prod[[k]]) ## removing NA values. That is, we keep the firms that have the complete obs for all variables
Productivity_list_mean[[k]] <- All_list_for_prod[[k]]  %>% 
  arrange(IDNR, Year, COMPCAT, NAICs_two_digit) %>%
  group_by(IDNR) %>% 
  filter(length(Year) > 5) %>%  ### we only keep those firms with more than 5 year obs. 
  summarize(LP_mu = mean(LP, na.rm = T), 
            CP_mu = mean(CP, na.rm = T),
            LP_change_mu = mean(LP_change, na.rm = T),
            CP_change_mu = mean(CP_change, na.rm = T),
            Zeta_mu = mean(Zeta, na.rm = T),
            EMPL_mu = mean(EMPL, na.rm = T),
            TOAS_mu = mean(TOAS, na.rm = T),
            RoC = mean(RoC, na.rm = T),
            RoC_RCEM = mean(RoC_RCEM, na.rm = T),
            WS = mean(WS, na.rm = T),
            PW_ratio = mean(PW_ratio, na.rm = T),
            C_com = mean(C_com, na.rm = T),
            PW_ratio_change = mean(PW_ratio_change, na.rm = T),
            COMPCAT = COMPCAT[1], 
            NAICs_two_digit = NAICs_two_digit[1]
            
            )
All_list_for_prod[[k]] <- 1
}

```


```{r}
save(Productivity_list_mean, file = "Productivity_list_mean.Rda")

```

```{r}
setwd("~/Desktop/Cleaned Rda/Productivity")
load("Productivity_list_mean.Rda")
```


```{r}
#library(heavy)
### the function for a scatterplot
scatter_fun <- function(dat_list, var_a_ind, var_b_ind, cut_neg, cut_pov, pdf_name, plot_name, var_x_name, var_y_name, log_ind){
   pdf(paste(pdf_name,".pdf", sep = ""), height = 15, width = 12)
  par(mfrow=c(5,4), mar=c(3, 2.5, 1, 1), mgp=c(1.1,.3,0), tck=-.01, oma=c(0,0,4,0))
  
  # legend in the first box
  plot(1,1, col = "white", yaxt = "n", xaxt = "n", xlab = NA, ylab = NA, bty = "n")
  legend("topleft", c("Small", "Medium", "Large", "Very Large"), xpd = NA, horiz = F, inset = c(0,0), bty = "n", pch = rep(20,4), col = colores_4, cex = 2)

for(k in 1:length(dat_list)){
  dat <- dat_list[[k]]
  dat <- subset(dat, EMPL_mu > 1) # removing self-employed firms
  var_a <- dat[,var_a_ind]
  var_b <- dat[,var_b_ind]
  
   d_frame <- as.data.frame(na.omit(cbind(var_a = var_a, var_b = var_b, size = dat$COMPCAT, pw = dat$PW_ratio, r = dat$RoC_RCEM)))
 names(d_frame) <- c("var_a", "var_b", "size", "pw", "r")
 
 d_frame_cut <- subset(d_frame, var_a > cut_neg & var_a < quantile(var_a, cut_pov) & var_b > quantile(var_b, cut_neg) & var_b < quantile(var_b, cut_pov))

 if(nrow( d_frame_cut ) <= 500){ # cut the countries with less than 500 firms
   print(k)
 } else if(log_ind == 1){ # log_ind == 1 means both variables will be in log-scale
   
     d_frame_cut <- subset(d_frame, var_a > 0 & var_a < quantile(var_a, cut_pov) & var_b > 0 & var_b < quantile(var_b, cut_pov)) # cutting negative VA firms
     
     d_frame_cut <- subset(d_frame_cut, var_a > quantile(var_a, cut_neg)  & var_b > quantile(var_b, cut_neg)) 
 
   d_frame_cut_s <- subset(d_frame_cut, size == "SMALL")
   d_frame_cut_m <- subset(d_frame_cut, size == "MEDIUM SIZED")
   d_frame_cut_l <- subset(d_frame_cut, size == "LARGE")
   d_frame_cut_vl <- subset(d_frame_cut, size == "VERY LARGE")
 
   colores_4 <- rainbow_hcl(4, end=300)
   #d_frame_cut <- subset(d_frame_cut, var_b < 0)
   plot(log(d_frame_cut$var_a),  log(d_frame_cut$var_b), pch = 20, cex = 0.5, yaxt = "n", xaxt = "n", cex.main = 1.2, xlab = var_x_name, ylab = var_y_name, main = paste(country_names[[k]]), col = "white", cex.lab = 1)
  
  points(log(d_frame_cut_s$var_a),  log(d_frame_cut_s$var_b), pch = 20, cex = 0.2, col = colores_4[[1]])
  points(log(d_frame_cut_m$var_a),  log(d_frame_cut_m$var_b), pch = 20, cex = 0.2, col = colores_4[[2]])
  points(log(d_frame_cut_l$var_a),  log(d_frame_cut_l$var_b), pch = 20, cex = 0.2, col = colores_4[[3]])
  points(log(d_frame_cut_vl$var_a),  log(d_frame_cut_vl$var_b), pch = 20, cex = 0.2, col = colores_4[[4]])
   
   abline(lm(log(d_frame_cut_s$var_b) ~ log(d_frame_cut_s$var_a )), col = colores_4[1]) 
   #abline( heavyLm(log(d_frame_cut_s$var_b) ~ log(d_frame_cut_s$var_a ), family = Student(df = 5)), col = colores_4[1]) 
   abline(lm(log(d_frame_cut_m$var_b) ~ log(d_frame_cut_m$var_a )), col = colores_4[2]) 
   abline(lm(log(d_frame_cut_l$var_b) ~ log(d_frame_cut_l$var_a )), col = colores_4[3]) 
   abline(lm(log(d_frame_cut_vl$var_b) ~ log(d_frame_cut_vl$var_a )), col = colores_4[4]) 
  
  #summary(lm(log(-d_frame_cut$var_b) ~ log(d_frame_cut$var_a )))
  axis(side = 1, lwd = 0.3, cex.axis=0.67)
  axis(side = 2, lwd = 0.3, cex.axis=0.67)

 #  legend(leg_loc, legend =   year_ind, pch = 1:length(  year_ind), col = colores_c[1:length(  year_ind)], bty='n', xpd=NA, cex = .7)
   
 } else if(log_ind == 2){ #log_ind == 2 means y variable is in log scale
     d_frame_cut <- subset(d_frame, var_a > quantile(var_a, cut_neg) & var_a < quantile(var_a, cut_pov) & var_b > 0 & var_b < quantile(var_b, cut_pov))
     
     
  d_frame_cut <- subset(d_frame_cut,  var_b > quantile(var_b, cut_neg))
  
   d_frame_cut_s <- subset(d_frame_cut, size == "SMALL")
   d_frame_cut_m <- subset(d_frame_cut, size == "MEDIUM SIZED")
   d_frame_cut_l <- subset(d_frame_cut, size == "LARGE")
   d_frame_cut_vl <- subset(d_frame_cut, size == "VERY LARGE")
 

   colores_4 <- rainbow_hcl(4, end=300)
   #d_frame_cut <- subset(d_frame_cut, var_b < 0)
   plot(d_frame_cut$var_a,  log(d_frame_cut$var_b), pch = 20, cex = 0.5, yaxt = "n", xaxt = "n", cex.main = 1.2, xlab = var_x_name, ylab = var_y_name, main = paste(country_names[[k]]), col = "white", cex.lab = 1)
  
  points(d_frame_cut_s$var_a,  log(d_frame_cut_s$var_b), pch = 20, cex = 0.2, col = colores_4[[1]])
  points(d_frame_cut_m$var_a,  log(d_frame_cut_m$var_b), pch = 20, cex = 0.2, col = colores_4[[2]])
  points(d_frame_cut_l$var_a,  log(d_frame_cut_l$var_b), pch = 20, cex = 0.2, col = colores_4[[3]])
  points(d_frame_cut_vl$var_a,  log(d_frame_cut_vl$var_b), pch = 20, cex = 0.2, col = colores_4[[4]])
   
   abline(lm(log(d_frame_cut_s$var_b) ~ d_frame_cut_s$var_a ), col = colores_4[1]) 
   abline(lm(log(d_frame_cut_m$var_b) ~ d_frame_cut_m$var_a ), col = colores_4[2]) 
   abline(lm(log(d_frame_cut_l$var_b) ~ d_frame_cut_l$var_a ), col = colores_4[3]) 
   abline(lm(log(d_frame_cut_vl$var_b) ~ d_frame_cut_vl$var_a ), col = colores_4[4]) 
  
  #summary(lm(log(-d_frame_cut$var_b) ~ log(d_frame_cut$var_a )))
  axis(side = 1, lwd = 0.3, cex.axis=0.67)
  axis(side = 2, lwd = 0.3, cex.axis=0.67)

 } else if(log_ind == 3){ #  log_ind == 3 means both variables are in log scale and the variable y is a growth rate variable 
    d_frame_cut <- subset(d_frame, var_a > -1 & var_a < quantile(var_a, cut_pov) & var_b > -1 & var_b < quantile(var_b, cut_pov))
 
    d_frame_cut <- subset(d_frame_cut, var_a > quantile(var_a, cut_neg) & var_b > quantile(var_b, cut_neg) )
    
   d_frame_cut_s <- subset(d_frame_cut, size == "SMALL")
   d_frame_cut_m <- subset(d_frame_cut, size == "MEDIUM SIZED")
   d_frame_cut_l <- subset(d_frame_cut, size == "LARGE")
   d_frame_cut_vl <- subset(d_frame_cut, size == "VERY LARGE")
 

    colores_4 <- rainbow_hcl(4, end=300)
   #d_frame_cut <- subset(d_frame_cut, var_b < 0)
   plot(log(d_frame_cut$var_a),  log(d_frame_cut$var_b + 1), pch = 20, cex = 0.5, yaxt = "n", xaxt = "n", cex.main = 1.2, xlab = var_x_name, ylab = var_y_name, main = paste(country_names[[k]]), col = "white", cex.lab = 1)
  
  points(log(d_frame_cut_s$var_a),  log(d_frame_cut_s$var_b + 1), pch = 20, cex = 0.2, col = colores_4[[1]])
  points(log(d_frame_cut_m$var_a),  log(d_frame_cut_m$var_b + 1), pch = 20, cex = 0.2, col = colores_4[[2]])
  points(log(d_frame_cut_l$var_a),  log(d_frame_cut_l$var_b + 1), pch = 20, cex = 0.2, col = colores_4[[3]])
  points(log(d_frame_cut_vl$var_a),  log(d_frame_cut_vl$var_b + 1), pch = 20, cex = 0.2, col = colores_4[[4]])
   
   abline(lm(log(d_frame_cut_s$var_b + 1) ~ log(d_frame_cut_s$var_a )), col = colores_4[1]) 
   abline(lm(log(d_frame_cut_m$var_b + 1) ~ log(d_frame_cut_m$var_a )), col = colores_4[2]) 
   abline(lm(log(d_frame_cut_l$var_b + 1) ~ log(d_frame_cut_l$var_a )), col = colores_4[3]) 
   abline(lm(log(d_frame_cut_vl$var_b + 1) ~ log(d_frame_cut_vl$var_a )), col = colores_4[4]) 
  
  #summary(lm(log(-d_frame_cut$var_b) ~ log(d_frame_cut$var_a )))
  axis(side = 1, lwd = 0.3, cex.axis=0.67)
  axis(side = 2, lwd = 0.3, cex.axis=0.67)


 } else{ # log_ind == 4 means the variable y is in log scale and is a growth rate variable
  d_frame_cut <- subset(d_frame, var_a > quantile(var_a, cut_neg) & var_a < quantile(var_a, cut_pov) & var_b > -1 & var_b < quantile(var_b, cut_pov))
  d_frame_cut <- subset(d_frame_cut,  var_b >  quantile(var_b, cut_neg))
 
   d_frame_cut_s <- subset(d_frame_cut, size == "SMALL")
   d_frame_cut_m <- subset(d_frame_cut, size == "MEDIUM SIZED")
   d_frame_cut_l <- subset(d_frame_cut, size == "LARGE")
   d_frame_cut_vl <- subset(d_frame_cut, size == "VERY LARGE")
 

   colores_4 <- rainbow_hcl(4, end=300)
   #d_frame_cut <- subset(d_frame_cut, var_b < 0)
   plot(d_frame_cut$var_a,  log(d_frame_cut$var_b + 1), pch = 20, cex = 0.5, yaxt = "n", xaxt = "n", cex.main = 1.2, xlab = var_x_name, ylab = var_y_name, main = paste(country_names[[k]]), col = "white", cex.lab = 1)
  
  points(d_frame_cut_s$var_a,  log(d_frame_cut_s$var_b + 1), pch = 20, cex = 0.2, col = colores_4[[1]])
  points(d_frame_cut_m$var_a,  log(d_frame_cut_m$var_b+ 1), pch = 20, cex = 0.2, col = colores_4[[2]])
  points(d_frame_cut_l$var_a,  log(d_frame_cut_l$var_b+ 1), pch = 20, cex = 0.2, col = colores_4[[3]])
  points(d_frame_cut_vl$var_a,  log(d_frame_cut_vl$var_b+ 1), pch = 20, cex = 0.2, col = colores_4[[4]])
   
   abline(lm(log(d_frame_cut_s$var_b+ 1) ~ d_frame_cut_s$var_a ), col = colores_4[1]) 
   abline(lm(log(d_frame_cut_m$var_b+ 1) ~ d_frame_cut_m$var_a ), col = colores_4[2]) 
   abline(lm(log(d_frame_cut_l$var_b+ 1) ~ d_frame_cut_l$var_a ), col = colores_4[3]) 
   abline(lm(log(d_frame_cut_vl$var_b+ 1) ~ d_frame_cut_vl$var_a ), col = colores_4[4]) 
  
  #summary(lm(log(-d_frame_cut$var_b) ~ log(d_frame_cut$var_a )))
  axis(side = 1, lwd = 0.3, cex.axis=0.67)
  axis(side = 2, lwd = 0.3, cex.axis=0.67)
 }
   }

 mtext(plot_name, side=3, line=1, outer=TRUE,cex= 1.4)
  dev.off()
 
}

```

```{r}

####  Level variables
setwd("~/Desktop/Figures")
lapply(Productivity_list_mean, function(x) dim(x))

names(Productivity_list_mean[[1]])

## TOAS_LP
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 8, var_b_ind = 2, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "TOAS_LP", plot_name = expression(paste("Scatter Plot of Total Asset and Labor Productivity")), var_x_name =  expression(paste("log(K)")),  var_y_name = expression(paste("log(x)")),log_ind =1)

## TOAS_CP
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 8, var_b_ind = 3, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "TOAS_CP", plot_name = expression(paste("Scatter Plot of Total Asset and Capital Productivity")), var_x_name =  expression(paste("log(K)")),  var_y_name = expression(paste("log(",rho,")")),log_ind =1)

## EMPL_LP
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 7, var_b_ind = 2, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "EMPL_LP", plot_name = expression(paste("Scatter Plot of Employment and Labor Productivity")), var_x_name =  expression(paste("log(L)")),  var_y_name = expression(paste("log(x)")),log_ind =1)

## EMPL_CP
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 7, var_b_ind = 3, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "EMPL_CP", plot_name = expression(paste("Scatter Plot of Employment and Capital Productivity")), var_x_name =  expression(paste("log(L)")),  var_y_name = expression(paste("log(",rho,")")),log_ind =1)

## C_Com_LP
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 13, var_b_ind = 2, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "C_Com_LP", plot_name = expression(paste("Scatter Plot of Capital Composition and Labor Productivity")), var_x_name =  expression(paste("log(",tau,")")),  var_y_name = expression(paste("log(x)")),log_ind =1)

## C_Com_CP
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 13, var_b_ind = 3, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "C_Com_CP", plot_name = expression(paste("Scatter Plot of Capital Composition and Capital Productivity")), var_x_name =  expression(paste("log(",tau,")")),  var_y_name = expression(paste("log(",rho,")")),log_ind =1)

# LP_CP
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 2, var_b_ind = 3, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "LP_CP", plot_name = expression(paste("Scatter Plot of Labor Productivity and Capital Productivity")), var_x_name =  expression(paste("log(x)")),  var_y_name = expression(paste("log(",rho,")")),log_ind =1)
```

```{r}
names(Productivity_list_mean[[1]])

## RoCE_LP (cut net is higher due to quite a few outliers)
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 10, var_b_ind = 2, cut_neg = 0.03, cut_pov = 0.99, pdf_name = "RoCE_LP", plot_name = expression(paste("Scatter Plot of Returns on Capital and Labor Productivity")), var_x_name =  expression(paste("r")),  var_y_name = expression(paste("log(x)")),log_ind =2)

## RoCE_CP
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 10, var_b_ind = 3, cut_neg = 0.02, cut_pov = 0.99, pdf_name = "RoCE_CP", plot_name = expression(paste("Scatter Plot of Returns on Capital and Capital Productivity")), var_x_name =  expression(paste("r")),  var_y_name = expression(paste("log(",rho,")")),log_ind =2)



```


```{r}
names(Productivity_list_mean[[1]])

## LP_LP_change
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 2, var_b_ind = 4, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "LP_LP_change", plot_name = expression(paste("Scatter Plot of Labor Productivity Level and Labor Productivity Growth")), var_x_name =  expression(paste("log(x)")),  var_y_name = expression(paste("log(",gamma,")")),log_ind = 3)

## CP_CP_change
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 3, var_b_ind = 5, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "CP_CP_change", plot_name = expression(paste("Scatter Plot of Capital Productivity Level and Capital Productivity Growth")), var_x_name =  expression(paste("log(K)")),  var_y_name = expression(paste("log(",chi,")")),log_ind =3)

## LP_Zeta
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 2, var_b_ind = 6, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "LP_Zeta", plot_name = expression(paste("Scatter Plot of Labor Productivity Level and TFP Growth")), var_x_name =  expression(paste("log(x)")),  var_y_name = expression(paste("log(",zeta,")")),log_ind = 3)

## CP_Zeta
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 3, var_b_ind = 6, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "CP_Zeta", plot_name = expression(paste("Scatter Plot of Capital Productivity Level and TFP Growth")), var_x_name =  expression(paste("log(K)")),  var_y_name = expression(paste("log(",zeta,")")),log_ind =3)



## C_com_LP_change
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 13, var_b_ind = 4, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "C_Com_LP_change", plot_name = expression(paste("Scatter Plot of Capital Composition Level and Labor Productivity Growth")), var_x_name =  expression(paste("log(",tau,")")),  var_y_name = expression(paste("log(",gamma,")")),log_ind = 3)

## C_com_CP_change
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 13, var_b_ind = 5, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "C_Com_CP_change", plot_name = expression(paste("Scatter Plot of Capital Composition Level and Capital Productivity Growth")), var_x_name =  expression(paste("log(",tau,")")),  var_y_name = expression(paste("log(",chi,")")),log_ind =3)

## C_com_Zeta
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 13, var_b_ind = 6, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "C_Com_Zeta", plot_name = expression(paste("Scatter Plot of Capital Composition Level and TFP Growth")), var_x_name =  expression(paste("log(",tau,")")),  var_y_name = expression(paste("log(",zeta,")")),log_ind = 3)

## TOAS_LP_change
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 8, var_b_ind = 4, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "TOAS_LP_change", plot_name = expression(paste("Scatter Plot of Total Asset and Labor Productivity Growth")), var_x_name =  expression(paste("log(K)")),  var_y_name = expression(paste("log(",gamma,")")),log_ind = 3)

## TOAS_CP_change
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 8, var_b_ind = 5, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "TOAS_CP_change", plot_name = expression(paste("Scatter Plot of Total Asset and Capital Productivity Growth")), var_x_name =  expression(paste("log(K)")),  var_y_name = expression(paste("log(",chi,")")),log_ind =3)

## TOAS_Zeta
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 8, var_b_ind = 6, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "TOAS_Zeta", plot_name = expression(paste("Scatter Plot of Total Asset and TFP Growth")), var_x_name =  expression(paste("log(K)")),  var_y_name = expression(paste("log(",zeta,")")),log_ind = 3)

## EMPL_LP_change
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 7, var_b_ind = 4, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "EMPL_LP_change", plot_name = expression(paste("Scatter Plot of  Employment and Labor Productivity Growth")), var_x_name =  expression(paste("log(L)")),  var_y_name = expression(paste("log(",gamma,")")),log_ind = 3)

## EMPL_CP_change
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 7, var_b_ind = 5, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "EMPL_CP_change", plot_name = expression(paste("Scatter Plot of  Employment and Capital Productivity Growth")), var_x_name =  expression(paste("log(L)")),  var_y_name = expression(paste("log(",chi,")")),log_ind =3)

## EMPL_Zeta
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 7, var_b_ind = 6, cut_neg = 0.01, cut_pov = 0.99, pdf_name = "EMPL_Zeta", plot_name = expression(paste("Scatter Plot of  Employment and TFP Growth")), var_x_name =  expression(paste("log(L)")),  var_y_name = expression(paste("log(",zeta,")")),log_ind = 3)



```


```{r}
names(Productivity_list_mean[[1]])

## RoCE_LP_change
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 10, var_b_ind = 4, cut_neg = 0.02, cut_pov = 0.98, pdf_name = "RoCE_LP_change", plot_name = expression(paste("Scatter Plot of Returns on Capital Level and Labor Productivity Growth")), var_x_name =  expression(paste("r")),  var_y_name = expression(paste("log(",gamma,")")),log_ind = 4)

## RoCE_CP_change
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 10, var_b_ind = 5, cut_neg = 0.02, cut_pov = 0.98, pdf_name = "RoCE_CP_change", plot_name = expression(paste("Scatter Plot of Returns on Capital and Capital Productivity Growth")), var_x_name =  expression(paste("r")),  var_y_name = expression(paste("log(",chi,")")),log_ind =4)

## RoCE_Zeta
scatter_fun(dat_list = Productivity_list_mean, var_a_ind = 10, var_b_ind = 6, cut_neg = 0.02, cut_pov = 0.98, pdf_name = "RoCE_Zeta", plot_name = expression(paste("Scatter Plot of Returns on Capital and TFP Growth")), var_x_name =  expression(paste("r")),  var_y_name = expression(paste("log(",zeta,")")),log_ind = 4)


```